Repository AWS-Cloud-School-6/AIWA-MCP-Frontend, pull requests merged in 2024-10, with the labels that each got.

#7 #4 [Feat] 로그인/회원가입
  aiwa-mcp-frontend/package-lock.json
  aiwa-mcp-frontend/package.json
  aiwa-mcp-frontend/src/Auth/Auth.js
  aiwa-mcp-frontend/src/Auth/components.js
  aiwa-mcp-frontend/src/Auth/formFields.js
  aiwa-mcp-frontend/src/index.js
Labels: enhancement

#11 #10 리다이렉션 매핑 config
  aiwa-mcp-frontend/src/Console/Features/Instance/AWS_instance_launch.js
  aiwa-mcp-frontend/src/Console/Features/Instance/GCP_instance_launch.js
  aiwa-mcp-frontend/src/Console/Features/Instance/Instance.js
  aiwa-mcp-frontend/src/Console/Features/Instance/index.js
  aiwa-mcp-frontend/src/Console/Features/Subnet/Subnet.js
  aiwa-mcp-frontend/src/Console/Features/Subnet/index.js
  aiwa-mcp-frontend/src/Console/Features/VPC/VPC.js
  aiwa-mcp-frontend/src/Console/Features/VPC/index.js
  aiwa-mcp-frontend/src/Console/Profile/Profile.js
  aiwa-mcp-frontend/src/Console/index.js
  aiwa-mcp-frontend/src/aws-exports.js
  aiwa-mcp-frontend/src/index.js
Labels: enhancement

#14 #13 vpc list 테이블 구현
  aiwa-mcp-frontend/src/Console/Console.js
  aiwa-mcp-frontend/src/Console/Features/VPC/VPC.js
  aiwa-mcp-frontend/src/Console/Features/VPC/VPC_Create.js
  aiwa-mcp-frontend/src/Console/Features/VPC/index.js
  aiwa-mcp-frontend/src/Console/Features/VPC/table/ActionButtons.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/AddCustomerButton.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/CustomerRow.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/CustomerTable.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/CustomerTable.module.css
  aiwa-mcp-frontend/src/Console/Features/VPC/table/CustomerTableContext.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/TableHeader.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/TablePagination.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/useCustomer.js
  aiwa-mcp-frontend/src/Console/index.js
  aiwa-mcp-frontend/src/Main/Main.js
  aiwa-mcp-frontend/src/index.js
  aiwa-mcp-frontend/src/ui-components/NavBarHeader2.jsx
Labels: enhancement

#17 #13 콘솔 vpc 구현
  aiwa-mcp-frontend/src/Console/Features/VPC/VPC.js
  aiwa-mcp-frontend/src/Console/Features/VPC/VPC_Create.js
  aiwa-mcp-frontend/src/Console/Features/VPC/table/CustomerRow.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/CustomerTable.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/CustomerTable.module.css
  aiwa-mcp-frontend/src/Console/Features/VPC/table/TableHeader.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/useCustomer.js
  aiwa-mcp-frontend/src/ui-components/NavBarHeader2.jsx
Labels: enhancement

#20 #19 [Test]: push 할 때 secret 변수 값 들어가지는지 테스트
  aiwa-mcp-frontend/.gitignore
  aiwa-mcp-frontend/src/Auth/Auth.js
Labels: test

#22 #21 [Feat] VPC API 구현
  aiwa-mcp-frontend/src/Console/Features/VPC/VPC_Create.js
  aiwa-mcp-frontend/src/Features/Instance/Instance.js
  aiwa-mcp-frontend/src/UserContext.js
  aiwa-mcp-frontend/src/index.js
Labels: enhancement

#24 #19 [Feat]: EC2 테이블 교체
  aiwa-mcp-frontend/src/Auth/Auth.js
  aiwa-mcp-frontend/src/Console/Console.js
  aiwa-mcp-frontend/src/Console/Features/VPC/VPC_Create.js
  aiwa-mcp-frontend/src/Console/Features/VPC/table/VPCTable.jsx
Labels: enhancement

#30 #29 [Feat]: Logout 문제 해결
  aiwa-mcp-frontend/src/Auth/Auth.js
  aiwa-mcp-frontend/src/Console/Console.js
  aiwa-mcp-frontend/src/Console/Features/Instance/Instance.js
  aiwa-mcp-frontend/src/Console/Features/VPC/VPC.js
  aiwa-mcp-frontend/src/Console/Features/VPC/VPC_Create.js
  aiwa-mcp-frontend/src/Console/Features/VPC/table/TableHeader.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/VPCTable.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/VPCTable.module.css
  aiwa-mcp-frontend/src/Console/NavBar/NavBar.jsx
  aiwa-mcp-frontend/src/Console/NavBar/NavBar.module.css
  aiwa-mcp-frontend/src/Console/NavBar/NavLinks.jsx
Labels: bug, enhancement

#33 #31 [Refactor]: api 주소 수정
  aiwa-mcp-frontend/src/Console/Console.js
  aiwa-mcp-frontend/src/Console/Features/Instance/table/EC2Table.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/VPC_Create.js
  aiwa-mcp-frontend/src/Console/Features/VPC/table/VPCTable.jsx
  aiwa-mcp-frontend/src/index.js
Labels: fix

#36 #35 [Feat] credential 입력 마이페이지 구현
  aiwa-mcp-frontend/src/Console/Console.js
  aiwa-mcp-frontend/src/Console/Features/Routetable/Routetable.js
  aiwa-mcp-frontend/src/Console/Features/Routetable/index.js
  aiwa-mcp-frontend/src/Console/Features/VPC/Sidebar/NavigationLink.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/Sidebar/NavigationSection.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/Sidebar/SidebarVpc.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/Sidebar/SidebarVpc.module.css
  aiwa-mcp-frontend/src/Console/Features/VPC/VPC.js
  aiwa-mcp-frontend/src/Console/Features/VPC/table/TableHeader.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/VPCRow.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/VPCTable.jsx
  aiwa-mcp-frontend/src/Console/SideBar/NavigationLink.jsx
  aiwa-mcp-frontend/src/Console/SideBar/NavigationLink.module.css
  aiwa-mcp-frontend/src/Console/SideBar/SidebarConsole.jsx
  aiwa-mcp-frontend/src/Console/SideBar/SidebarConsole.module.css
  aiwa-mcp-frontend/src/Console/SideBar/UserProfile.jsx
  aiwa-mcp-frontend/src/Console/SideBar/UserProfile.module.css
Labels: enhancement

#40 #38 Subnet 생성 버그 처리 완료
  aiwa-mcp-frontend/src/Console/Features/Subnet/Subnet_Create.js
  aiwa-mcp-frontend/src/Console/Features/Subnet/table/SubnetTable.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/VPCTable.jsx
Labels: bug

#42 #39 [Fix]: 체크박스 에러 해결
  aiwa-mcp-frontend/src/Console/Features/VPC/table/VPCTable.jsx
Labels: fix

#44 #43 [Fix]: 체크박스 에러 해결 및 테이블 수정
  aiwa-mcp-frontend/src/Console/Features/VPC/Sidebar/NavigationLink.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/Subnet.js
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/Subnet_Create.js
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/index.js
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/table/ActionButtons.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/table/AddSubnetButton.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/table/SubnetRow.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/table/SubnetTable.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/table/SubnetTable.module.css
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/table/TableHeader.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/table/TablePagination.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/index.js
  aiwa-mcp-frontend/src/Console/index.js
Labels: fix

#48 #47 [!BREAKING CHANGE]: API url 수정
  aiwa-mcp-frontend/src/Console/Console.js
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/table/SubnetTable.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/VPCTable.jsx
  aiwa-mcp-frontend/src/Console/SideBar/SidebarConsole.jsx
  aiwa-mcp-frontend/src/index.js
Labels: bug

#49 #47 [!BREAKING CHANGE]: API url 수정
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/Subnet_Create.js
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/table/SubnetTable.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/VPCTable.jsx
Labels: bug

#50 #47 [!BREAKING CHANGE]: API url 수정
  aiwa-mcp-frontend/src/Console/Features/VPC/table/VPCTable.jsx
Labels: bug

#53 #52 Subnet Delete + delete 막기 구현
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/table/ActionButtons.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/table/SubnetTable.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/table/SubnetTable.module.css
Labels: enhancement

#54 #51 [Feat]: 인터넷 게이트웨이 구현
  aiwa-mcp-frontend/src/Console/Features/VPC/InternetGateway/InternetGateway.js
  aiwa-mcp-frontend/src/Console/Features/VPC/InternetGateway/table/AddSubnetButton.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/InternetGateway/table/CreateIGModal.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/InternetGateway/table/CreateIGModal.module.css
  aiwa-mcp-frontend/src/Console/Features/VPC/InternetGateway/table/IGButtons.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/InternetGateway/table/IGRow.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/InternetGateway/table/IGTable.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/InternetGateway/table/IGTable.module.css
  aiwa-mcp-frontend/src/Console/Features/VPC/InternetGateway/table/TableHeader.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/InternetGateway/table/TablePagination.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/Sidebar/SidebarVpc.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/Subnet_Create.js
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/index.js
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/table/SubnetRow.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/table/TableHeader.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/index.js
Labels: enhancement

#57 56 fix 인터넷 게이트웨이 여러 개 삭제 기능 수정
  aiwa-mcp-frontend/src/Console/Features/VPC/InternetGateway/table/IGRow.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/InternetGateway/table/IGTable.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/InternetGateway/table/IGTable.module.css
  aiwa-mcp-frontend/src/Console/Features/VPC/InternetGateway/table/TableHeader.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/VPC_Create.js
  aiwa-mcp-frontend/src/Console/Features/VPC/table/VPCTable.jsx
Labels: fix

#60 #59 Refactor: subnet UI 수정
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/table/SubnetRow.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/table/SubnetTable.module.css
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/table/TableHeader.jsx
Labels: enhancement

#61 #55 Subnet 삭제 + Creating State in VPC 완료
  aiwa-mcp-frontend/package-lock.json
  aiwa-mcp-frontend/package.json
  aiwa-mcp-frontend/src/Console/Console.js
  aiwa-mcp-frontend/src/Console/Features/VPC/NotificationContext.js
  aiwa-mcp-frontend/src/Console/Features/VPC/VPC.js
  aiwa-mcp-frontend/src/Console/Features/VPC/VPC_Create.js
  aiwa-mcp-frontend/src/Console/Features/VPC/index.js
  aiwa-mcp-frontend/src/Console/Features/VPC/table/DeleteVPCModal.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/DeleteVPCModal.module.css
  aiwa-mcp-frontend/src/Console/Features/VPC/table/VPCTable.jsx
Labels: enhancement
