Repository AWS-Cloud-School-6/AIWA-MCP-Frontend, pull requests merged in 2024-11, with the labels that each got.

#65 #64 [Feat]: routetable 기능 구현
  aiwa-mcp-frontend/src/Console/Console.js
  aiwa-mcp-frontend/src/Console/Features/Instance/table/EC2Table.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/InternetGateway/table/CreateIGModal.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/InternetGateway/table/IGTable.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/NatGateway/table/CreateNatModal.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/NatGateway/table/NatTable.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/RouteTable/RouteTable.js
  aiwa-mcp-frontend/src/Console/Features/VPC/RouteTable/table/CreateRTModal.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/RouteTable/table/CreateRTModal.module.css
  aiwa-mcp-frontend/src/Console/Features/VPC/RouteTable/table/RTRow.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/RouteTable/table/RTTable.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/RouteTable/table/RTTable.module.css
  aiwa-mcp-frontend/src/Console/Features/VPC/RouteTable/table/TableHeader.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/RouteTable/table/TablePagination.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/Subnet_Create.js
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/table/SubnetTable.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/VPC.js
  aiwa-mcp-frontend/src/Console/Features/VPC/VPC_Create.js
  aiwa-mcp-frontend/src/Console/Features/VPC/index.js
  aiwa-mcp-frontend/src/Console/Features/VPC/table/DeleteVPCModal.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/VPCTable.jsx
  aiwa-mcp-frontend/src/Console/SideBar/SidebarConsole.jsx
  aiwa-mcp-frontend/src/index.js
  path/to/file
Labels: enhancement

#67 #66 [Fix]: 액세스키 기능 수정
  aiwa-mcp-frontend/.gitignore
  aiwa-mcp-frontend/src/Console/Console.js
  aiwa-mcp-frontend/src/Console/Features/VPC/InternetGateway/table/CreateIGModal.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/InternetGateway/table/IGTable.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/NatGateway/table/CreateNatModal.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/NatGateway/table/NatTable.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/RouteTable/table/CreateRTModal.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/RouteTable/table/RTTable.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/Subnet_Create.js
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/table/SubnetTable.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/DeleteVPCModal.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/VPCTable.jsx
  aiwa-mcp-frontend/src/Console/NavBar/NavBar.jsx
  aiwa-mcp-frontend/src/Console/NavBar/NavBar.module.css
  aiwa-mcp-frontend/src/Console/SideBar/SidebarConsole.jsx
  aiwa-mcp-frontend/src/Console/SideBar/SidebarConsole.module.css
  aiwa-mcp-frontend/src/UserContext.js
Labels: fix

#68 66 fix 액세스키 기능 수정
  aiwa-mcp-frontend/src/Console/NavBar/NavBar.jsx
Labels: fix

#79 #76 [Fix]: 액세스키 인증 url로 변경
  .github/workflows/main.yml
  aiwa-mcp-frontend/src/Console/Console.js
Labels: fix

#81 #75 GCP 경로 추가 및 Instance Side Bar 수정
  aiwa-mcp-frontend/src/Console/Features/Instance/Instance.js
  aiwa-mcp-frontend/src/Console/Features/Instance/Sidebar/NavigationLink.jsx
  aiwa-mcp-frontend/src/Console/Features/Instance/Sidebar/NavigationSection.jsx
  aiwa-mcp-frontend/src/Console/Features/Instance/Sidebar/SidebarEc2.jsx
  aiwa-mcp-frontend/src/Console/Features/Instance/Sidebar/SidebarEc2.module.css
  aiwa-mcp-frontend/src/Console/Features/Instance/table/DeleteEC2Modal.jsx
  aiwa-mcp-frontend/src/Console/Features/Instance/table/DeleteEC2Modal.module.css
  aiwa-mcp-frontend/src/Console/Features/Instance/table/EC2Table.jsx
  aiwa-mcp-frontend/src/Console/Features/Instance/table/EC2Table.module.css
  aiwa-mcp-frontend/src/index.js
Labels: enhancement

#84 73 feat console 페이지
  aiwa-mcp-frontend/package-lock.json
  aiwa-mcp-frontend/package.json
  aiwa-mcp-frontend/src/Console/Console.css
  aiwa-mcp-frontend/src/Console/Console.js
  aiwa-mcp-frontend/src/Console/NavBar/NavBar.jsx
  aiwa-mcp-frontend/src/Console/index.js
Labels: enhancement

#85 #83 Fix: EC2 page 수정
  aiwa-mcp-frontend/src/Console/Features/Instance/table/EC2Row.jsx
  aiwa-mcp-frontend/src/Console/Features/Instance/table/EC2Table.jsx
Labels: fix

#89 #88 Routing Table Fix 하나만 요청시 하나만 뜨게
  aiwa-mcp-frontend/src/Console/Features/VPC/RouteTable/table/RTTable.jsx
Labels: enhancement, fix

#90 #Feat: ENI page 추가
  aiwa-mcp-frontend/src/Console/Features/Instance/eni/eni.js
  aiwa-mcp-frontend/src/Console/Features/Instance/eni/table/CreateENIModal.jsx
  aiwa-mcp-frontend/src/Console/Features/Instance/eni/table/CreateENIModal.module.css
  aiwa-mcp-frontend/src/Console/Features/Instance/eni/table/ENIRow.jsx
  aiwa-mcp-frontend/src/Console/Features/Instance/eni/table/ENITable.jsx
  aiwa-mcp-frontend/src/Console/Features/Instance/eni/table/ENITable.module.css
  aiwa-mcp-frontend/src/Console/Features/Instance/eni/table/TableHeader.jsx
  aiwa-mcp-frontend/src/Console/Features/Instance/eni/table/TablePagination.jsx
Labels: enhancement

#91 [Fix]: eni 라우팅 추가
  aiwa-mcp-frontend/src/Console/Features/Instance/index.js
Labels: fix

#95 #92 EC2 Get API 동시 호출
  aiwa-mcp-frontend/src/Console/Features/Instance/table/EC2Row.jsx
  aiwa-mcp-frontend/src/Console/Features/Instance/table/EC2Table.jsx
  aiwa-mcp-frontend/src/Console/Features/Instance/table/TableHeader.jsx
Labels: enhancement

#96 #94 [Fix]: GCP project id 값 불러오기
  aiwa-mcp-frontend/src/Console/Console.js
  aiwa-mcp-frontend/src/Console/SideBar/SidebarConsole.jsx
  aiwa-mcp-frontend/src/UserContext.js
  aiwa-mcp-frontend/src/index.js
Labels: fix

#99 #97 [Fix]: 액세스키 입력 로직 수정
  aiwa-mcp-frontend/src/Console/Console.js
Labels: fix

#101 #100 [Fix]: GCP json 키파일 등록 문제 해결
  aiwa-mcp-frontend/src/Console/Console.js
  aiwa-mcp-frontend/src/Console/SideBar/SidebarConsole.jsx
Labels: fix

#102 #100 [Fix]: GCP json 키 파일 등록 후 project id null 값 뜨는 에러 해결
  aiwa-mcp-frontend/src/Console/Console.js
  aiwa-mcp-frontend/src/UserContext.js
Labels: fix

#105 #104 [Fix]: accessKey 전역 변수로 선언
  aiwa-mcp-frontend/src/UserContext.js
Labels: fix

#107 #106 Feat: Ec2 API 경우의 수 추가
  aiwa-mcp-frontend/src/Console/Features/Instance/table/EC2Table.jsx
Labels: enhancement

#109 #108 Feat: Subnet API 동시 호출
  aiwa-mcp-frontend/src/Console/Console.js
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/table/SubnetRow.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/table/SubnetTable.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/table/TableHeader.jsx
Labels: enhancement

#110 [Fix]: VPC 테이블 수정
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/Subnet.js
  aiwa-mcp-frontend/src/Console/Features/VPC/VPC.js
  aiwa-mcp-frontend/src/Console/Features/VPC/table/ActionButtons.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/CreateVPCModal.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/DeleteVPCModal.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/TableHeader.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/VPCRow.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/VPCTable.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/VPCTable.module.css
Labels: fix

#112 #103 [Fix]: VPC 테이블 수정
  aiwa-mcp-frontend/src/Console/Features/VPC/table/CreateVPCModal.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/VPCRow.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/VPCTable.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/VPCTable.module.css
  aiwa-mcp-frontend/src/images/aws_icon.png
  aiwa-mcp-frontend/src/images/gcp_icon.png
Labels: fix

#113 103 fix 리소스 테이블 수정
  aiwa-mcp-frontend/src/Console/Console.js
  aiwa-mcp-frontend/src/Console/Features/Instance/Instance.js
  aiwa-mcp-frontend/src/Console/Features/Instance/Sidebar/SidebarEc2.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/Sidebar/SidebarVpc.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/table/CreateSubnetModal.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/table/SubnetRow.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/table/SubnetTable.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/table/SubnetTable.module.css
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/table/TableHeader.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/DeleteVPCModal.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/TableHeader.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/VPCRow.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/VPCTable.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/VPCTable.module.css
Labels: fix

#116 #115 [Design] 마이그레이션 페이지 구현
  aiwa-mcp-frontend/src/Console/Console.js
  aiwa-mcp-frontend/src/Console/Features/VPC/VPC.js
  aiwa-mcp-frontend/src/Console/Migration/Migration.js
  aiwa-mcp-frontend/src/Console/Profile/Profile.js
  aiwa-mcp-frontend/src/Console/SideBar/SidebarConsole.jsx
  aiwa-mcp-frontend/src/Console/index.js
Labels: design

#121 #[Fix]: 인스턴스 생성 기능 수정
  aiwa-mcp-frontend/src/Console/Features/Instance/Instance.js
  aiwa-mcp-frontend/src/Console/Features/Instance/Sidebar/SidebarEc2.module.css
  aiwa-mcp-frontend/src/Console/Features/Instance/index.js
  aiwa-mcp-frontend/src/Console/Features/Instance/table/ActionButtons.jsx
  aiwa-mcp-frontend/src/Console/Features/Instance/table/CreateEC2Modal.jsx
  aiwa-mcp-frontend/src/Console/Features/Instance/table/CreateEC2Modal.module.css
  aiwa-mcp-frontend/src/Console/Features/Instance/table/EC2Row.jsx
  aiwa-mcp-frontend/src/Console/Features/Instance/table/EC2Table.jsx
  aiwa-mcp-frontend/src/Console/Features/Instance/table/EC2Table.module.css
  aiwa-mcp-frontend/src/Console/Features/Instance/table/TableHeader.jsx
  aiwa-mcp-frontend/src/Console/Features/NotificationContext.js
  aiwa-mcp-frontend/src/Console/Features/VPC/Subnet/table/CreateSubnetModal.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/VPC.js
  aiwa-mcp-frontend/src/Console/Features/VPC/index.js
  aiwa-mcp-frontend/src/Console/Features/VPC/table/CreateVPCModal.jsx
  aiwa-mcp-frontend/src/Console/Features/VPC/table/DeleteVPCModal.jsx
Labels: fix
